package com.greatm.biz.taskdao;

import com.greatm.biz.entity.TTaskScheduleEntity;
import com.greatm.biz.entity.TTaskScheduleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TTaskScheduleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    long countByExample(TTaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int deleteByExample(TTaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int insert(TTaskScheduleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int insertSelective(TTaskScheduleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    List<TTaskScheduleEntity> selectByExample(TTaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    TTaskScheduleEntity selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTaskScheduleEntity record, @Param("example") TTaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTaskScheduleEntity record, @Param("example") TTaskScheduleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TTaskScheduleEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TTaskScheduleEntity record);
}