package com.greatm.biz.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TTaskScheduleExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public TTaskScheduleExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(Long value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(Long value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(Long value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(Long value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(Long value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(Long value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<Long> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<Long> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(Long value1, Long value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(Long value1, Long value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andApplyCountIsNull() {
            addCriterion("apply_count is null");
            return (Criteria) this;
        }

        public Criteria andApplyCountIsNotNull() {
            addCriterion("apply_count is not null");
            return (Criteria) this;
        }

        public Criteria andApplyCountEqualTo(Integer value) {
            addCriterion("apply_count =", value, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountNotEqualTo(Integer value) {
            addCriterion("apply_count <>", value, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountGreaterThan(Integer value) {
            addCriterion("apply_count >", value, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("apply_count >=", value, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountLessThan(Integer value) {
            addCriterion("apply_count <", value, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountLessThanOrEqualTo(Integer value) {
            addCriterion("apply_count <=", value, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountIn(List<Integer> values) {
            addCriterion("apply_count in", values, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountNotIn(List<Integer> values) {
            addCriterion("apply_count not in", values, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountBetween(Integer value1, Integer value2) {
            addCriterion("apply_count between", value1, value2, "applyCount");
            return (Criteria) this;
        }

        public Criteria andApplyCountNotBetween(Integer value1, Integer value2) {
            addCriterion("apply_count not between", value1, value2, "applyCount");
            return (Criteria) this;
        }

        public Criteria andHiredIdIsNull() {
            addCriterion("hired_id is null");
            return (Criteria) this;
        }

        public Criteria andHiredIdIsNotNull() {
            addCriterion("hired_id is not null");
            return (Criteria) this;
        }

        public Criteria andHiredIdEqualTo(Long value) {
            addCriterion("hired_id =", value, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdNotEqualTo(Long value) {
            addCriterion("hired_id <>", value, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdGreaterThan(Long value) {
            addCriterion("hired_id >", value, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdGreaterThanOrEqualTo(Long value) {
            addCriterion("hired_id >=", value, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdLessThan(Long value) {
            addCriterion("hired_id <", value, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdLessThanOrEqualTo(Long value) {
            addCriterion("hired_id <=", value, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdIn(List<Long> values) {
            addCriterion("hired_id in", values, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdNotIn(List<Long> values) {
            addCriterion("hired_id not in", values, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdBetween(Long value1, Long value2) {
            addCriterion("hired_id between", value1, value2, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredIdNotBetween(Long value1, Long value2) {
            addCriterion("hired_id not between", value1, value2, "hiredId");
            return (Criteria) this;
        }

        public Criteria andHiredNameIsNull() {
            addCriterion("hired_name is null");
            return (Criteria) this;
        }

        public Criteria andHiredNameIsNotNull() {
            addCriterion("hired_name is not null");
            return (Criteria) this;
        }

        public Criteria andHiredNameEqualTo(String value) {
            addCriterion("hired_name =", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameNotEqualTo(String value) {
            addCriterion("hired_name <>", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameGreaterThan(String value) {
            addCriterion("hired_name >", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameGreaterThanOrEqualTo(String value) {
            addCriterion("hired_name >=", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameLessThan(String value) {
            addCriterion("hired_name <", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameLessThanOrEqualTo(String value) {
            addCriterion("hired_name <=", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameLike(String value) {
            addCriterion("hired_name like", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameNotLike(String value) {
            addCriterion("hired_name not like", value, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameIn(List<String> values) {
            addCriterion("hired_name in", values, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameNotIn(List<String> values) {
            addCriterion("hired_name not in", values, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameBetween(String value1, String value2) {
            addCriterion("hired_name between", value1, value2, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredNameNotBetween(String value1, String value2) {
            addCriterion("hired_name not between", value1, value2, "hiredName");
            return (Criteria) this;
        }

        public Criteria andHiredTimeIsNull() {
            addCriterion("hired_time is null");
            return (Criteria) this;
        }

        public Criteria andHiredTimeIsNotNull() {
            addCriterion("hired_time is not null");
            return (Criteria) this;
        }

        public Criteria andHiredTimeEqualTo(Date value) {
            addCriterion("hired_time =", value, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeNotEqualTo(Date value) {
            addCriterion("hired_time <>", value, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeGreaterThan(Date value) {
            addCriterion("hired_time >", value, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("hired_time >=", value, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeLessThan(Date value) {
            addCriterion("hired_time <", value, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeLessThanOrEqualTo(Date value) {
            addCriterion("hired_time <=", value, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeIn(List<Date> values) {
            addCriterion("hired_time in", values, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeNotIn(List<Date> values) {
            addCriterion("hired_time not in", values, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeBetween(Date value1, Date value2) {
            addCriterion("hired_time between", value1, value2, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andHiredTimeNotBetween(Date value1, Date value2) {
            addCriterion("hired_time not between", value1, value2, "hiredTime");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIsNull() {
            addCriterion("task_status is null");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIsNotNull() {
            addCriterion("task_status is not null");
            return (Criteria) this;
        }

        public Criteria andTaskStatusEqualTo(Byte value) {
            addCriterion("task_status =", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotEqualTo(Byte value) {
            addCriterion("task_status <>", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusGreaterThan(Byte value) {
            addCriterion("task_status >", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("task_status >=", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLessThan(Byte value) {
            addCriterion("task_status <", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLessThanOrEqualTo(Byte value) {
            addCriterion("task_status <=", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIn(List<Byte> values) {
            addCriterion("task_status in", values, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotIn(List<Byte> values) {
            addCriterion("task_status not in", values, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusBetween(Byte value1, Byte value2) {
            addCriterion("task_status between", value1, value2, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("task_status not between", value1, value2, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNull() {
            addCriterion("pay_status is null");
            return (Criteria) this;
        }

        public Criteria andPayStatusIsNotNull() {
            addCriterion("pay_status is not null");
            return (Criteria) this;
        }

        public Criteria andPayStatusEqualTo(Byte value) {
            addCriterion("pay_status =", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotEqualTo(Byte value) {
            addCriterion("pay_status <>", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThan(Byte value) {
            addCriterion("pay_status >", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("pay_status >=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThan(Byte value) {
            addCriterion("pay_status <", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusLessThanOrEqualTo(Byte value) {
            addCriterion("pay_status <=", value, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusIn(List<Byte> values) {
            addCriterion("pay_status in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotIn(List<Byte> values) {
            addCriterion("pay_status not in", values, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusBetween(Byte value1, Byte value2) {
            addCriterion("pay_status between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andPayStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("pay_status not between", value1, value2, "payStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusIsNull() {
            addCriterion("complain_status is null");
            return (Criteria) this;
        }

        public Criteria andComplainStatusIsNotNull() {
            addCriterion("complain_status is not null");
            return (Criteria) this;
        }

        public Criteria andComplainStatusEqualTo(Byte value) {
            addCriterion("complain_status =", value, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusNotEqualTo(Byte value) {
            addCriterion("complain_status <>", value, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusGreaterThan(Byte value) {
            addCriterion("complain_status >", value, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("complain_status >=", value, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusLessThan(Byte value) {
            addCriterion("complain_status <", value, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusLessThanOrEqualTo(Byte value) {
            addCriterion("complain_status <=", value, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusIn(List<Byte> values) {
            addCriterion("complain_status in", values, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusNotIn(List<Byte> values) {
            addCriterion("complain_status not in", values, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusBetween(Byte value1, Byte value2) {
            addCriterion("complain_status between", value1, value2, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andComplainStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("complain_status not between", value1, value2, "complainStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusIsNull() {
            addCriterion("review_status is null");
            return (Criteria) this;
        }

        public Criteria andReviewStatusIsNotNull() {
            addCriterion("review_status is not null");
            return (Criteria) this;
        }

        public Criteria andReviewStatusEqualTo(Byte value) {
            addCriterion("review_status =", value, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusNotEqualTo(Byte value) {
            addCriterion("review_status <>", value, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusGreaterThan(Byte value) {
            addCriterion("review_status >", value, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("review_status >=", value, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusLessThan(Byte value) {
            addCriterion("review_status <", value, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusLessThanOrEqualTo(Byte value) {
            addCriterion("review_status <=", value, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusIn(List<Byte> values) {
            addCriterion("review_status in", values, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusNotIn(List<Byte> values) {
            addCriterion("review_status not in", values, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusBetween(Byte value1, Byte value2) {
            addCriterion("review_status between", value1, value2, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andReviewStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("review_status not between", value1, value2, "reviewStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusIsNull() {
            addCriterion("audi_status is null");
            return (Criteria) this;
        }

        public Criteria andAudiStatusIsNotNull() {
            addCriterion("audi_status is not null");
            return (Criteria) this;
        }

        public Criteria andAudiStatusEqualTo(Byte value) {
            addCriterion("audi_status =", value, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusNotEqualTo(Byte value) {
            addCriterion("audi_status <>", value, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusGreaterThan(Byte value) {
            addCriterion("audi_status >", value, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("audi_status >=", value, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusLessThan(Byte value) {
            addCriterion("audi_status <", value, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusLessThanOrEqualTo(Byte value) {
            addCriterion("audi_status <=", value, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusIn(List<Byte> values) {
            addCriterion("audi_status in", values, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusNotIn(List<Byte> values) {
            addCriterion("audi_status not in", values, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusBetween(Byte value1, Byte value2) {
            addCriterion("audi_status between", value1, value2, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("audi_status not between", value1, value2, "audiStatus");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonIsNull() {
            addCriterion("audi_over_reason is null");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonIsNotNull() {
            addCriterion("audi_over_reason is not null");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonEqualTo(String value) {
            addCriterion("audi_over_reason =", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonNotEqualTo(String value) {
            addCriterion("audi_over_reason <>", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonGreaterThan(String value) {
            addCriterion("audi_over_reason >", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonGreaterThanOrEqualTo(String value) {
            addCriterion("audi_over_reason >=", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonLessThan(String value) {
            addCriterion("audi_over_reason <", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonLessThanOrEqualTo(String value) {
            addCriterion("audi_over_reason <=", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonLike(String value) {
            addCriterion("audi_over_reason like", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonNotLike(String value) {
            addCriterion("audi_over_reason not like", value, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonIn(List<String> values) {
            addCriterion("audi_over_reason in", values, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonNotIn(List<String> values) {
            addCriterion("audi_over_reason not in", values, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonBetween(String value1, String value2) {
            addCriterion("audi_over_reason between", value1, value2, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiOverReasonNotBetween(String value1, String value2) {
            addCriterion("audi_over_reason not between", value1, value2, "audiOverReason");
            return (Criteria) this;
        }

        public Criteria andAudiTimeIsNull() {
            addCriterion("audi_time is null");
            return (Criteria) this;
        }

        public Criteria andAudiTimeIsNotNull() {
            addCriterion("audi_time is not null");
            return (Criteria) this;
        }

        public Criteria andAudiTimeEqualTo(Date value) {
            addCriterion("audi_time =", value, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeNotEqualTo(Date value) {
            addCriterion("audi_time <>", value, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeGreaterThan(Date value) {
            addCriterion("audi_time >", value, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("audi_time >=", value, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeLessThan(Date value) {
            addCriterion("audi_time <", value, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeLessThanOrEqualTo(Date value) {
            addCriterion("audi_time <=", value, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeIn(List<Date> values) {
            addCriterion("audi_time in", values, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeNotIn(List<Date> values) {
            addCriterion("audi_time not in", values, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeBetween(Date value1, Date value2) {
            addCriterion("audi_time between", value1, value2, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiTimeNotBetween(Date value1, Date value2) {
            addCriterion("audi_time not between", value1, value2, "audiTime");
            return (Criteria) this;
        }

        public Criteria andAudiIdIsNull() {
            addCriterion("audi_id is null");
            return (Criteria) this;
        }

        public Criteria andAudiIdIsNotNull() {
            addCriterion("audi_id is not null");
            return (Criteria) this;
        }

        public Criteria andAudiIdEqualTo(Long value) {
            addCriterion("audi_id =", value, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdNotEqualTo(Long value) {
            addCriterion("audi_id <>", value, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdGreaterThan(Long value) {
            addCriterion("audi_id >", value, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdGreaterThanOrEqualTo(Long value) {
            addCriterion("audi_id >=", value, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdLessThan(Long value) {
            addCriterion("audi_id <", value, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdLessThanOrEqualTo(Long value) {
            addCriterion("audi_id <=", value, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdIn(List<Long> values) {
            addCriterion("audi_id in", values, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdNotIn(List<Long> values) {
            addCriterion("audi_id not in", values, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdBetween(Long value1, Long value2) {
            addCriterion("audi_id between", value1, value2, "audiId");
            return (Criteria) this;
        }

        public Criteria andAudiIdNotBetween(Long value1, Long value2) {
            addCriterion("audi_id not between", value1, value2, "audiId");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNull() {
            addCriterion("complete_time is null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIsNotNull() {
            addCriterion("complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeEqualTo(Date value) {
            addCriterion("complete_time =", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotEqualTo(Date value) {
            addCriterion("complete_time <>", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThan(Date value) {
            addCriterion("complete_time >", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("complete_time >=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThan(Date value) {
            addCriterion("complete_time <", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("complete_time <=", value, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeIn(List<Date> values) {
            addCriterion("complete_time in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotIn(List<Date> values) {
            addCriterion("complete_time not in", values, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("complete_time between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("complete_time not between", value1, value2, "completeTime");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidIsNull() {
            addCriterion("complete_accoid is null");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidIsNotNull() {
            addCriterion("complete_accoid is not null");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidEqualTo(Long value) {
            addCriterion("complete_accoid =", value, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidNotEqualTo(Long value) {
            addCriterion("complete_accoid <>", value, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidGreaterThan(Long value) {
            addCriterion("complete_accoid >", value, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidGreaterThanOrEqualTo(Long value) {
            addCriterion("complete_accoid >=", value, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidLessThan(Long value) {
            addCriterion("complete_accoid <", value, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidLessThanOrEqualTo(Long value) {
            addCriterion("complete_accoid <=", value, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidIn(List<Long> values) {
            addCriterion("complete_accoid in", values, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidNotIn(List<Long> values) {
            addCriterion("complete_accoid not in", values, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidBetween(Long value1, Long value2) {
            addCriterion("complete_accoid between", value1, value2, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCompleteAccoidNotBetween(Long value1, Long value2) {
            addCriterion("complete_accoid not between", value1, value2, "completeAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelTimeIsNull() {
            addCriterion("cancel_time is null");
            return (Criteria) this;
        }

        public Criteria andCancelTimeIsNotNull() {
            addCriterion("cancel_time is not null");
            return (Criteria) this;
        }

        public Criteria andCancelTimeEqualTo(Date value) {
            addCriterion("cancel_time =", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeNotEqualTo(Date value) {
            addCriterion("cancel_time <>", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeGreaterThan(Date value) {
            addCriterion("cancel_time >", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("cancel_time >=", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeLessThan(Date value) {
            addCriterion("cancel_time <", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeLessThanOrEqualTo(Date value) {
            addCriterion("cancel_time <=", value, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeIn(List<Date> values) {
            addCriterion("cancel_time in", values, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeNotIn(List<Date> values) {
            addCriterion("cancel_time not in", values, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeBetween(Date value1, Date value2) {
            addCriterion("cancel_time between", value1, value2, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelTimeNotBetween(Date value1, Date value2) {
            addCriterion("cancel_time not between", value1, value2, "cancelTime");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidIsNull() {
            addCriterion("cancel_accoid is null");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidIsNotNull() {
            addCriterion("cancel_accoid is not null");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidEqualTo(Long value) {
            addCriterion("cancel_accoid =", value, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidNotEqualTo(Long value) {
            addCriterion("cancel_accoid <>", value, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidGreaterThan(Long value) {
            addCriterion("cancel_accoid >", value, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidGreaterThanOrEqualTo(Long value) {
            addCriterion("cancel_accoid >=", value, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidLessThan(Long value) {
            addCriterion("cancel_accoid <", value, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidLessThanOrEqualTo(Long value) {
            addCriterion("cancel_accoid <=", value, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidIn(List<Long> values) {
            addCriterion("cancel_accoid in", values, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidNotIn(List<Long> values) {
            addCriterion("cancel_accoid not in", values, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidBetween(Long value1, Long value2) {
            addCriterion("cancel_accoid between", value1, value2, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelAccoidNotBetween(Long value1, Long value2) {
            addCriterion("cancel_accoid not between", value1, value2, "cancelAccoid");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIsNull() {
            addCriterion("cancel_reason is null");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIsNotNull() {
            addCriterion("cancel_reason is not null");
            return (Criteria) this;
        }

        public Criteria andCancelReasonEqualTo(String value) {
            addCriterion("cancel_reason =", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotEqualTo(String value) {
            addCriterion("cancel_reason <>", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonGreaterThan(String value) {
            addCriterion("cancel_reason >", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonGreaterThanOrEqualTo(String value) {
            addCriterion("cancel_reason >=", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLessThan(String value) {
            addCriterion("cancel_reason <", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLessThanOrEqualTo(String value) {
            addCriterion("cancel_reason <=", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonLike(String value) {
            addCriterion("cancel_reason like", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotLike(String value) {
            addCriterion("cancel_reason not like", value, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonIn(List<String> values) {
            addCriterion("cancel_reason in", values, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotIn(List<String> values) {
            addCriterion("cancel_reason not in", values, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonBetween(String value1, String value2) {
            addCriterion("cancel_reason between", value1, value2, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCancelReasonNotBetween(String value1, String value2) {
            addCriterion("cancel_reason not between", value1, value2, "cancelReason");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_schedule
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_task_schedule
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}